import Contact from "../models/contactModel.js";
import nodemailer from "nodemailer";

export const submitContactForm = async (req, res) => {
  try {
    const { name, contact, location, email, message } = req.body;

    if (!name || !contact || !location || !email || !message) {
      return res
        .status(400)
        .json({ success: false, message: "All fields are required!" });
    }

    // ✅ Save contact data to MongoDB
    const newContact = await Contact.create({
      name,
      contact,
      location,
      email,
      message,
    });

    // ✅ Setup Gmail SMTP transport
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    // ✅ Compose admin alert email
    const adminMailOptions = {
      from: `"Seva Sai Alert System" <${process.env.EMAIL_USER}>`,
      to: process.env.ADMIN_EMAIL,
      subject: "📩 New Contact Form Submission - Seva Sai Nursing Bureau",
      html: `
        <div style="font-family: Arial, sans-serif; padding: 10px; background-color: #f4f8ff;">
          <h2 style="color: #0066cc;">📩 New Contact Form Submission</h2>
          <p><strong>👤 Name:</strong> ${name}</p>
          <p><strong>📞 Contact:</strong> ${contact}</p>
          <p><strong>📍 Location:</strong> ${location}</p>
          <p><strong>✉️ Email:</strong> ${email}</p>
          <p><strong>💬 Message:</strong> ${message}</p>
          <p><em>🕒 Received: ${new Date().toLocaleString()}</em></p>
          <hr>
          <p style="font-size: 0.9em; color: #555;">
            This email was automatically generated by Seva Sai Nursing Bureau's contact form.
          </p>
        </div>
      `,
    };

    // ✅ Send admin alert email
    await transporter.sendMail(adminMailOptions);
    console.log("✅ Email alert sent to admin");

    // ✅ Optional: Auto-reply to user (thank-you email)
    /*
    const userMailOptions = {
      from: `"Seva Sai Nursing Bureau" <${process.env.EMAIL_USER}>`,
      to: email,
      subject: "Thank You for Contacting Seva Sai Nursing Bureau",
      html: `
        <div style="font-family: Arial, sans-serif; padding: 10px; background-color: #f4f8ff;">
          <h2 style="color: #009688;">🙏 Thank You, ${name}!</h2>
          <p>We have received your message:</p>
          <blockquote style="border-left: 3px solid #009688; padding-left: 10px; color: #333;">
            ${message}
          </blockquote>
          <p>Our team will get back to you shortly at <strong>${email}</strong> or <strong>${contact}</strong>.</p>
          <p style="color: #555;">Warm regards,<br><b>Seva Sai Nursing Bureau Team</b></p>
        </div>
      `,
    };
    await transporter.sendMail(userMailOptions);
    console.log("📩 Auto-reply sent to user");
    */

    // ✅ Respond back to frontend
    res.status(201).json({
      success: true,
      data: newContact,
      message: "Form submitted successfully & email alert sent!",
    });
  } catch (error) {
    console.error("❌ Error submitting contact form:", error);
    res
      .status(500)
      .json({ success: false, message: "Server error while submitting form." });
  }
};
